package HTTP::MobileAgent::DoCoMoDisplayMap;
# This file is autogenerated by makedocomomap
# in HTTP-MobileAgent distribution

use strict;
require Exporter;
use base qw(Exporter);

use vars qw(@EXPORT_OK $DisplayMap);
@EXPORT_OK = qw($DisplayMap);

$DisplayMap = {
  'N504iS' => {
    'width' => 160,
    'height' => 180,
    'depth' => 65536,
    'color' => 1
  },
  'F212i' => {
    'width' => 132,
    'height' => 136,
    'depth' => 65536,
    'color' => 1
  },
  'P503iS' => {
    'width' => 120,
    'height' => 130,
    'depth' => 256,
    'color' => 1
  },
  'D503i' => {
    'width' => 132,
    'height' => 126,
    'depth' => 4096,
    'color' => 1
  },
  'F503i' => {
    'width' => 120,
    'height' => 130,
    'depth' => 256,
    'color' => 1
  },
  'P209iS' => {
    'width' => 96,
    'height' => 87,
    'depth' => 256,
    'color' => 1
  },
  'P2102V' => {
    'width' => 176,
    'height' => 198,
    'depth' => 262144,
    'color' => 1
  },
  'N503i' => {
    'width' => 118,
    'height' => 128,
    'depth' => 4096,
    'color' => 1
  },
  'P503i' => {
    'width' => 120,
    'height' => 130,
    'depth' => 256,
    'color' => 1
  },
  'F502it' => {
    'width' => 96,
    'height' => 91,
    'depth' => 256,
    'color' => 1
  },
  'ER209i' => {
    'width' => 120,
    'height' => 72,
    'depth' => 2,
    'color' => ''
  },
  'R692i' => {
    'width' => 96,
    'height' => 98,
    'depth' => 4096,
    'color' => 1
  },
  'SH251i' => {
    'width' => 120,
    'height' => 130,
    'depth' => 65536,
    'color' => 1
  },
  'N211iS' => {
    'width' => 118,
    'height' => 128,
    'depth' => 4096,
    'color' => 1
  },
  'SO211i' => {
    'width' => 120,
    'height' => 112,
    'depth' => 4096,
    'color' => 1
  },
  'SH821i' => {
    'width' => 96,
    'height' => 78,
    'depth' => 256,
    'color' => 1
  },
  'N251iS' => {
    'width' => 132,
    'height' => 140,
    'depth' => 65536,
    'color' => 1
  },
  'SO502i' => {
    'width' => 120,
    'height' => 120,
    'depth' => 4,
    'color' => ''
  },
  'N502it' => {
    'width' => 118,
    'height' => 128,
    'depth' => 256,
    'color' => 1
  },
  'D504i' => {
    'width' => 132,
    'height' => 144,
    'depth' => 262144,
    'color' => 1
  },
  'SO502iWM' => {
    'width' => 120,
    'height' => 113,
    'depth' => 256,
    'color' => 1
  },
  'F504i' => {
    'width' => 132,
    'height' => 136,
    'depth' => 65536,
    'color' => 1
  },
  'D209i' => {
    'width' => 96,
    'height' => 90,
    'depth' => 256,
    'color' => 1
  },
  'F209i' => {
    'width' => 96,
    'height' => 91,
    'depth' => 256,
    'color' => 1
  },
  'F661i' => {
    'width' => 132,
    'height' => 136,
    'depth' => 65536,
    'color' => 1
  },
  'N504i' => {
    'width' => 160,
    'height' => 180,
    'depth' => 65536,
    'color' => 1
  },
  'P504i' => {
    'width' => 132,
    'height' => 144,
    'depth' => 65536,
    'color' => 1
  },
  'N209i' => {
    'width' => 108,
    'height' => 82,
    'depth' => 4,
    'color' => ''
  },
  'P209i' => {
    'width' => 96,
    'height' => 87,
    'depth' => 4,
    'color' => ''
  },
  'R209i' => {
    'width' => 96,
    'height' => 72,
    'depth' => 4,
    'color' => ''
  },
  'F503iS' => {
    'width' => 120,
    'height' => 130,
    'depth' => 4096,
    'color' => 1
  },
  'SO212i' => {
    'width' => 120,
    'height' => 112,
    'depth' => 65536,
    'color' => 1
  },
  'D210i' => {
    'width' => 96,
    'height' => 91,
    'depth' => 256,
    'color' => 1
  },
  'F210i' => {
    'width' => 96,
    'height' => 113,
    'depth' => 256,
    'color' => 1
  },
  'N503iS' => {
    'width' => 118,
    'height' => 128,
    'depth' => 4096,
    'color' => 1
  },
  'D501i' => {
    'width' => 96,
    'height' => 72,
    'depth' => 2,
    'color' => ''
  },
  'SO503i' => {
    'width' => 120,
    'height' => 113,
    'depth' => 65536,
    'color' => 1
  },
  'F501i' => {
    'width' => 112,
    'height' => 84,
    'depth' => 2,
    'color' => ''
  },
  'P504iS' => {
    'width' => 132,
    'height' => 144,
    'depth' => 65536,
    'color' => 1
  },
  'D505i' => {
    'width' => 240,
    'height' => 270,
    'depth' => 262144,
    'color' => 1
  },
  'N210i' => {
    'width' => 118,
    'height' => 113,
    'depth' => 256,
    'color' => 1
  },
  'P210i' => {
    'width' => 96,
    'height' => 91,
    'depth' => 256,
    'color' => 1
  },
  'N501i' => {
    'width' => 118,
    'height' => 128,
    'depth' => 2,
    'color' => ''
  },
  'P501i' => {
    'width' => 96,
    'height' => 120,
    'depth' => 2,
    'color' => ''
  },
  'N2001' => {
    'width' => 118,
    'height' => 128,
    'depth' => 4096,
    'color' => 1
  },
  'N2002' => {
    'width' => 118,
    'height' => 128,
    'depth' => 65536,
    'color' => 1
  },
  'P2002' => {
    'width' => 118,
    'height' => 128,
    'depth' => 65536,
    'color' => 1
  },
  'D251iS' => {
    'width' => 132,
    'height' => 144,
    'depth' => 262144,
    'color' => 1
  },
  'KO209i' => {
    'width' => 96,
    'height' => 96,
    'depth' => 256,
    'color' => 1
  },
  'D2101V' => {
    'width' => 120,
    'height' => 130,
    'depth' => 262144,
    'color' => 1
  },
  'F671iS' => {
    'width' => 160,
    'height' => 120,
    'depth' => 65536,
    'color' => 1
  },
  'P211iS' => {
    'width' => 120,
    'height' => 130,
    'depth' => 65536,
    'color' => 1
  },
  'D211i' => {
    'width' => 100,
    'height' => 91,
    'depth' => 4096,
    'color' => 1
  },
  'F211i' => {
    'width' => 96,
    'height' => 113,
    'depth' => 4096,
    'color' => 1
  },
  'P251iS' => {
    'width' => 132,
    'height' => 144,
    'depth' => 65536,
    'color' => 1
  },
  'D502i' => {
    'width' => 96,
    'height' => 90,
    'depth' => 256,
    'color' => 1
  },
  'SO504i' => {
    'width' => 120,
    'height' => 112,
    'depth' => 65536,
    'color' => 1
  },
  'D251i' => {
    'width' => 132,
    'height' => 144,
    'depth' => 262144,
    'color' => 1
  },
  'F502i' => {
    'width' => 96,
    'height' => 91,
    'depth' => 256,
    'color' => 1
  },
  'F251i' => {
    'width' => 132,
    'height' => 140,
    'depth' => 65536,
    'color' => 1
  },
  'P2101V' => {
    'width' => 163,
    'height' => 182,
    'depth' => 262144,
    'color' => 1
  },
  'N211i' => {
    'width' => 118,
    'height' => 128,
    'depth' => 4096,
    'color' => 1
  },
  'F671i' => {
    'width' => 120,
    'height' => 126,
    'depth' => 256,
    'color' => 1
  },
  'P211i' => {
    'width' => 120,
    'height' => 130,
    'depth' => 65536,
    'color' => 1
  },
  'F2051' => {
    'width' => 176,
    'height' => 182,
    'depth' => 65536,
    'color' => 1
  },
  'N502i' => {
    'width' => 118,
    'height' => 128,
    'depth' => 4,
    'color' => ''
  },
  'T2101V' => {
    'width' => 176,
    'height' => 144,
    'depth' => 262144,
    'color' => 1
  },
  'N251i' => {
    'width' => 132,
    'height' => 140,
    'depth' => 65536,
    'color' => 1
  },
  'R211i' => {
    'width' => 96,
    'height' => 98,
    'depth' => 4096,
    'color' => 1
  },
  'SH251iS' => {
    'width' => 176,
    'height' => 187,
    'depth' => 65536,
    'color' => 1
  },
  'P502i' => {
    'width' => 96,
    'height' => 117,
    'depth' => 4,
    'color' => ''
  },
  'N821i' => {
    'width' => 118,
    'height' => 128,
    'depth' => 4,
    'color' => ''
  },
  'P821i' => {
    'width' => 118,
    'height' => 128,
    'depth' => 4,
    'color' => ''
  },
  'SH2101V' => {
    'width' => 800,
    'height' => 600,
    'depth' => 65536,
    'color' => 1
  },
  'N2051' => {
    'width' => 176,
    'height' => 198,
    'depth' => 65536,
    'color' => 1
  },
  'KO210i' => {
    'width' => 96,
    'height' => 96,
    'depth' => 256,
    'color' => 1
  },
  'SO503iS' => {
    'width' => 120,
    'height' => 113,
    'depth' => 65536,
    'color' => 1
  },
  'D503iS' => {
    'width' => 132,
    'height' => 126,
    'depth' => 4096,
    'color' => 1
  },
  'R691i' => {
    'width' => 96,
    'height' => 72,
    'depth' => 4,
    'color' => ''
  },
  'NM502i' => {
    'width' => 111,
    'height' => 106,
    'depth' => 2,
    'color' => ''
  },
  'F504iS' => {
    'width' => 132,
    'height' => 136,
    'depth' => 65536,
    'color' => 1
  },
  'SO210i' => {
    'width' => 120,
    'height' => 113,
    'depth' => 256,
    'color' => 1
  }
};


1;
